### ISSUE TITLE
[Bug] Checkpoint Transition missing? (Glow near instant after a period of time)

### ISSUE THREAD

**Issue by CDAGaming** [MBU-Team/OpenMBU#66]

**Comment by HumanGamer** [comment]
Likely related to #36

**Comment by HumanGamer** [comment]
I was looking into this and it seems to render both the off and on version of the checkpoint at the same time, then remove the off version when it's fully transitioned. I'm not sure why this is happening.

**Comment by HumanGamer** [comment]
So from what I can see from testing, there are 2 layers. The on layer and the off layer. The off layer is above the on layer. The animation works by turning on the bottom layer and fading out the top one. For some reason the fade animation isn't working on the top layer. So the bottom one gets turned on, then when the animation is complete, the off layer on top disappears instead of gradually fading away.
